export const AppActions = {
  SET_URL: "SET_DATA",
  SET_TITLE: "SET_TITLE",
  SET_SLIDE_SIZE: "SET_SLIDE_SIZE",
  SET_THUMBS: "SET_THUMBS",
  SET_SLIDES: "SET_SLIDES",
  SET_INVALID_URL: "SET_INVALID_URL",
};
